# Generated by Django 4.1.6 on 2023-02-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("complete", models.BooleanField(default=False)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
